/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalchess;
import animalchess.board.Board;
import animalchess.board.Tiles.*;
import animalchess.animals.*;
import animalchess.exceptions.InvalidMovementException;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {

}
