/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalchess;

import animalchess.utils.EventManager;

public class App {

    private static EventManager eventManager;

    public static void main(String[] args) {
        eventManager = new EventManager();
    }

    public static EventManager getEventManager() {
        return eventManager;
    }

}
