/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalchess;

import animalchess.board.Board;
import animalchess.game.GameUI;

public class App {
	private static GameUI ui;
	private static Board board;
    public static void main(String[] args) {
    	ui = GameUI.getInstance();
    }
}
