/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalchess;

import java.awt.Dimension;

import javax.swing.JFrame;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.setMinimumSize(new Dimension(1000,1000));
        frame.setLocationRelativeTo(null);
        
        frame.setVisible(true);
    }
}
